version: '3.8'

services:
  server:
    build: .
    environment:
      # Get token from .env
      - DISCORD_BOT_CHANNEL
      - DISCORD_BOT_TOKEN
      - HOST
      - JAVA_MAX_MEMORY=8G
      - JAVA_MIN_MEMORY=1G
      - RCON_PASSWORD=rcon-password
      - SERVER_JAR_FILE=server.jar
    ports:
      - 25565:25565
    volumes:
      - .:/minecraft-vanilla
